# Generated by Django 5.0.4 on 2024-04-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_leads', '0002_alter_salesleads_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesleads',
            name='comments',
            field=models.TextField(default='Customer Request'),
        ),
    ]
