# Generated by Django 5.0.4 on 2024-04-10 02:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_leads', '0003_salesleads_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesLeads',
            new_name='SalesLead',
        ),
    ]
