# Generated by Django 5.0.4 on 2024-04-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_leads', '0004_rename_salesleads_saleslead'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslead',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
