# Generated by Django 5.0.4 on 2024-04-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_calculator', '0002_loancalculator_down_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancalculator',
            name='num_of_months',
            field=models.IntegerField(default=0),
        ),
    ]
