# Generated by Django 5.0.4 on 2024-04-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_calculator', '0003_alter_loancalculator_num_of_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancalculator',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
