# Generated by Django 5.0.4 on 2024-04-10 02:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees_vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeesVendors',
            new_name='EmployeeVendor',
        ),
    ]
