# Generated by Django 5.0.4 on 2024-04-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_vendors', '0002_rename_employeesvendors_employeevendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeevendor',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employeevendor',
            name='title',
            field=models.CharField(default='Vendor or Job Title', max_length=200),
        ),
    ]
