# Generated by Django 5.0.4 on 2024-04-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_vendors', '0003_remove_employeevendor_job_title_employeevendor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeevendor',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
