# Generated by Django 5.0.4 on 2024-04-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_vendors', '0004_employeevendor_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevendor',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeevendor',
            name='vendor_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
